version: '3.7'

services:
  helloworld-service:
    build:
      context: .
      args:
        VERSION: ${REVISION:-TRAVIS_COMMIT}
      target: builder
    image: hello/world-service
    restart: on-failure
    entrypoint: APP_ENV
